### ISSUE TITLE
Blog Creation Mods Snippet No longer Working

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsbcommons/bp-site-moderation#1]
Hey @r-a-y 

We are running into issues with this snippet: https://gist.github.com/mrjarbenne/070c2c63c77799689a84

When users attempt to use the check box, they get an error that they need to enter a site name, even though all the fields are populated.  

http://www.screencast.com/t/B828Xjps

**Comment by r-a-y** [comment]
Updated gist:
https://gist.github.com/r-a-y/6cd2588cde1faa1d1744

Problem was the 'disabled' attribute blocks the POST submission.  Using 'readonly' fixes this.

**Comment by mrjarbenne** [comment]
That did it. Thanks.
